Repository Saharoc-game/Battle-boss, pull requests merged in 2025-04, with the labels that each got.

#2 Фикс
  BatleBoss.py
Labels: hotfix

#3 Два новых подкласса!
  BatleBoss.py
Labels: Новое

#6 СРОЧНЫЙ ФИКС
  BatleBoss.py
Labels: hotfix

#7 Скажем нет монолиту!
  BatleBoss.py
  boss.py
  inventory.py
  player.py
Labels: Новое

#8 модульность
  BatleBoss.py
  core/boss.py
  core/inventory.py
  core/player.py
  git/.gitignore
Labels: Новое

#9 Меняем полностью механику инвентаря + тесты
  BatleBoss.py
  core/boss.py
  core/inventory.py
  core/player.py
  test_/test_boss.py
  test_/test_inventory.py
Labels: Новое

#10 test 1 BatleBoss.py
  BatleBoss.py
Labels: Новое

#12 New sigma
  BatleBossrecords.txt
  core/boss.py
  core/inventory.py
  core/player.py
Labels: Новое, dontmerge

#13 Добавляем способности боссам
  BatleBoss.py
  core/boss.py
  test_/test_boss.py
  test_/test_inventory.py
Labels: Новое

#18 Переделываем инвентарь... Снова..((
  BattleBoss.py
  core/inventory.py
  core/player.py
  test_/test_inventory.py
Labels: Новое
